export const WS_CONNECT_TO_GAMESERVER = "WS_CONNECT_TO_GAMESERVER";
export const WS_CONNECTED_TO_GAMESERVER = "WS_CONNECTED_TO_GAMESERVER";
export const WS_DISCONNECT_FROM_GAMESERVER = "WS_DISCONNECT_FROM_GAMESERVER";
export const WS_DISCONNECTED_FROM_GAMESERVER = "WS_DISCONNECTED_FROM_GAMESERVER";