export const WS_CONNECT_TO_GAMESERVER = "WS_CONNECT_TO_GAMESERVER";
export const WS_CONNECTED_TO_GAMESERVER = "WS_CONNECTED_TO_GAMESERVER";
export const WS_DISCONNECT_FROM_GAMESERVER = "WS_DISCONNECT_FROM_GAMESERVER";
export const WS_DISCONNECTED_FROM_GAMESERVER = "WS_DISCONNECTED_FROM_GAMESERVER";
export const WS_SEND_MESSAGE = "WS_SEND_MESSAGE";
export const MOVE_PLAYER = "MOVE_PLAYER";
export const GET_REALM_STATE = "GET_REALM_STATE";
export const GOT_REALM_STATE = "GOT_REALM_STATE";